export type StratSignal = {
  signal_id: string;
  symbol_id: string;
  timeframe: string;
  ts: string;
  bar_type: string;
  previous_bar_type: string | null;
  pattern: string | null;
  direction: string | null;
  trigger_price: number | null;
  trigger_stop: number | null;
  invalidation: string | null;
  timeframe_continuity: Record<string, string> | null;
  quality_score: number | null;
  can_create_trade_alone: boolean;
  created_at?: string | null;
};

export type StratTriggerPlan = {
  symbol_id: string;
  timeframe: string;
  latest_bar_ts: string | null;
  latest_bar_type: string | null;
  previous_bar_type: string | null;
  status: string;
  pattern: string | null;
  direction: string | null;
  trigger_price: number | null;
  trigger_stop: number | null;
  order_type: string | null;
  stop_limit_price: number | null;
  max_entry_price: number | null;
  risk_per_share: number | null;
  risk_distance_pct: number | null;
  atr_14: number | null;
  distance_to_sma_20_pct: number | null;
  consecutive_2u_count: number;
  timeframe_continuity: Record<string, string> | null;
  no_chase_rules: Array<Record<string, unknown>>;
  can_create_trade_alone: boolean;
};
